INSERT INTO "TEACHER"("TNO", "TNAME", "TSEX", "TPOSITION", "TSALARY", "TPWD") VALUES ('T001', '张三', '男', '教授', '30000', '123456');
INSERT INTO "TEACHER"("TNO", "TNAME", "TSEX", "TPOSITION", "TSALARY", "TPWD") VALUES ('T002', '李四', '男', '教授', '28000', 'T002');
INSERT INTO "TEACHER"("TNO", "TNAME", "TSEX", "TPOSITION", "TSALARY", "TPWD") VALUES ('T003', '王五', '女', '副教授', '25000', 'T003');
INSERT INTO "TEACHER"("TNO", "TNAME", "TSEX", "TPOSITION", "TSALARY", "TPWD") VALUES ('T004', '赵六', '男', '教授', '35000', 'T004');
INSERT INTO "TEACHER"("TNO", "TNAME", "TSEX", "TPOSITION", "TSALARY", "TPWD") VALUES ('T005', '孙七', '女', '讲师', '18000', 'T005');
INSERT INTO "TEACHER"("TNO", "TNAME", "TSEX", "TPOSITION", "TSALARY", "TPWD") VALUES ('T008', '刘强', '男', '教授', '35000', 'boss');
